global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Microsoft.EntityFrameworkCore;
global using MatchmakingSignalingServer.Domain.GameSessionEntities;
global using MatchmakingSignalingServer.Domain.GameSessionEntities.ValueTypes;
global using MatchmakingSignalingServer.Domain;
